import { ArrowLeft } from 'lucide-react';
import { Link } from 'react-router';
import { Navigation } from '../components/Navigation';
import { Footer } from '../components/Footer';

export default function WhyCakesRiseUnevenly() {
  const config = {
    WhyCakesFallAfterBaking: { title: "Why Cakes Fall After Baking", desc: "Discover why a perfectly risen cake collapses as it cools — and the structural fixes that keep it tall.", emoji: "📉", from: "rose-500", to: "red-600", gradient: "from-rose-50 via-red-50 to-orange-50", content: "A cake that rises beautifully then collapses after leaving the oven hasn't had enough time to set its structure. The air and steam that lifted it escape before proteins and starches fully coagulate, leaving a fragile scaffold that crumples under its own weight.", causes: [{ title: "Under-Baked Interior", body: "The most common cause. If the egg protein and starch network hasn't fully set, the cake collapses as soon as gas escapes on cooling.", fix: "Use a toothpick — it should come out with just a few moist crumbs. The internal temp should reach 200–210°F." }, { title: "Oven Door Opened Too Early", body: "Cold air rushing in during the first 20 minutes drops oven temperature, popping bubbles before structure has set.", fix: "Don't open the oven for at least the first 75% of bake time. Use the oven light to check." }, { title: "Too Much Leavening", body: "Over-leavened cakes rise aggressively then collapse — the structure can't support the excessive expansion.", fix: "Measure leavening with level teaspoons. Even 1/4 tsp too much baking soda causes collapse." }] },
    WhyCakesTasteDry: { title: "Why Cakes Taste Dry", desc: "Understand what strips moisture from cake crumb and how to bake moist, tender cakes every time.", emoji: "🏜️", from: "amber-500", to: "orange-600", gradient: "from-amber-50 via-orange-50 to-yellow-50", content: "A dry cake has lost or never had sufficient moisture in its crumb. Dryness comes from over-baking, too much flour, insufficient fat, or improper storage — often a combination of all four.", causes: [{ title: "Over-Baked", body: "Every extra minute drives more moisture from the crumb. Cakes continue baking on the hot pan after removal.", fix: "Check early — pull when a toothpick shows moist crumbs. Let carryover heat finish the last few degrees." }, { title: "Too Much Flour", body: "Excess flour absorbs available moisture from the batter, leaving the finished cake dry and crumbly.", fix: "Weigh flour: 1 cup = 120–125g. Scooping packs in 20–30% extra flour." }, { title: "Not Enough Fat", body: "Fat coats proteins and locks moisture in the crumb structure. Reducing fat below recipe amounts directly causes dryness.", fix: "Don't substitute low-fat ingredients in cake recipes. Oil-based cakes stay moister longer than butter cakes." }] },
    WhyCakesTurnGummy: { title: "Why Cakes Turn Gummy", desc: "Find out why cakes develop a dense, gummy, sticky crumb — and the starch science behind fixing it.", emoji: "🫠", from: "pink-500", to: "purple-600", gradient: "from-pink-50 via-purple-50 to-rose-50", content: "Gummy cake texture is a starch problem. When starch granules absorb too much moisture and don't fully gelatinize and dry out during baking, they remain swollen and sticky — creating that unpleasant dense, wet, gummy crumb.", causes: [{ title: "Under-Baked", body: "Insufficient baking time leaves starch granules in a partially gelatinized state — swollen with water but not set into a firm structure. The result is gummy and wet.", fix: "Bake until internal temp reaches 200–210°F. A toothpick should come out clean or with dry crumbs only." }, { title: "Too Much Liquid", body: "Excess liquid (eggs, milk, oil) gives starch more water to absorb than it can properly handle during baking. The surplus moisture makes the crumb gummy.", fix: "Measure liquids precisely. Don't add extra eggs or oil beyond the recipe." }, { title: "Opened Oven Too Soon", body: "Temperature drop from an early oven opening can cause partial starch re-gelatinization in the cooling batter, creating gummy pockets.", fix: "Keep the oven closed for at least 20–25 minutes into baking." }] },
    WhyCakesRiseUnevenly: { title: "Why Cakes Rise Unevenly", desc: "Learn why one side of your cake is higher than the other — and how pan prep, oven calibration, and mixing fix it.", emoji: "⛰️", from: "teal-500", to: "green-600", gradient: "from-teal-50 via-green-50 to-emerald-50", content: "An uneven rise produces a tilted cake that's difficult to layer and frost. The cause is always differential heat — one part of the cake bakes faster than another, causing unequal expansion and setting.", causes: [{ title: "Oven Hot Spots", body: "Almost all home ovens have areas that run hotter than others. Batter nearest the hot spot rises and sets first, while cooler areas continue expanding, creating a tilt.", fix: "Rotate the pan 180° halfway through baking. Use an oven thermometer to map your oven's temperature distribution." }, { title: "Batter Not Level in Pan", body: "Batter poured unevenly into the pan creates thickness variations. Thinner areas bake faster and set lower; thicker areas rise higher.", fix: "Tap the pan on the counter several times after filling to level the batter. Use a spatula to spread evenly." }, { title: "Oven Rack Not Level", body: "A tilted rack causes batter to settle to one side, creating a thicker section that rises higher.", fix: "Check that your oven rack is level using a small level tool. Adjust oven feet if needed." }] },
    WhyCakesTurnRubbery: { title: "Why Cakes Turn Rubbery", desc: "Discover why cakes develop a tough, rubbery texture instead of a tender crumb — and how mixing and fat control prevent it.", emoji: "🦑", from: "indigo-500", to: "purple-600", gradient: "from-indigo-50 via-purple-50 to-blue-50", content: "Rubbery cake is a gluten problem. Tender cake crumb requires minimal gluten development — just enough to hold structure. Over-develop the gluten and you get a tough, elastic, bread-like texture that bounces back instead of melting in your mouth.", causes: [{ title: "Over-Mixing After Adding Flour", body: "Every stroke after flour is added builds more gluten. Overdeveloped gluten creates an elastic network — exactly what you want in bread, exactly what you don't want in cake.", fix: "Add flour in 3 additions, alternating with liquid. Fold gently. Stop mixing the moment flour disappears." }, { title: "Wrong Flour Type", body: "Bread flour or all-purpose flour with high protein content (12%+) develops more gluten than cake flour (8% protein). Using bread flour in cake recipes guarantees rubbery results.", fix: "Use cake flour for delicate layer cakes. If using all-purpose, replace 2 tbsp per cup with cornstarch to reduce protein content." }, { title: "Too Little Fat", body: "Fat coats flour proteins and physically prevents gluten formation — this is called shortening the gluten. Insufficient fat leaves more proteins free to form gluten bonds.", fix: "Don't reduce fat in cake recipes. Fat is a tenderizer, not just a flavor ingredient." }] },
    WhyCakesStickToCoolingRack: { title: "Why Cakes Stick to Cooling Racks", desc: "Find out why cakes bond to wire cooling racks and how to prevent tearing when transferring warm cakes.", emoji: "🫢", from: "orange-500", to: "red-500", gradient: "from-orange-50 via-red-50 to-rose-50", content: "A warm cake placed directly on a wire rack can bond to the metal wires through caramelized sugar on its base or sides. This is especially common with glazed or sticky cakes and those with thin crusts.", causes: [{ title: "Placing Cake While Still Hot", body: "Very hot cakes have a moist, sticky surface. Direct contact with metal wires allows caramelized sugars to bond, and the soft structure can indent permanently from wire pressure.", fix: "Cool the cake in the pan for 10–15 minutes first. The surface firms slightly and caramelized sugar cools to a less adhesive state." }, { title: "Glazed or Sticky Surface", body: "Any glaze, syrup, or high-sugar crust dramatically increases the bonding surface with the wire rack.", fix: "Place a sheet of parchment paper on the wire rack before inverting glazed cakes. The parchment releases cleanly once fully cooled." }, { title: "Rack Not Greased for Delicate Cakes", body: "Very light, delicate cakes (angel food, chiffon) can tear on any rough surface when warm.", fix: "Lightly spray the cooling rack with cooking spray for delicate cakes. Some bakers cool angel food cakes inverted on a bottle neck to prevent any surface contact." }] }
  }['WhyCakesRiseUnevenly'];
  
  return (
    <div className={`min-h-screen bg-gradient-to-br ${config.gradient}`}>
      <Navigation />
      <article className="max-w-4xl mx-auto px-6 py-16">
        <Link to="/" className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground mb-8 transition-colors"><ArrowLeft className="w-4 h-4" />Back to Home</Link>
        <header className="mb-12">
          <div className={`inline-flex items-center gap-2 bg-gradient-to-r from-${config.from} to-${config.to} text-white px-4 py-2 rounded-full text-sm mb-6`}>Cake Science</div>
          <h1 className={`text-5xl md:text-6xl mb-6 bg-gradient-to-r from-${config.from} to-${config.to} bg-clip-text text-transparent`}>{config.title}</h1>
          <p className="text-xl text-muted-foreground">{config.desc}</p>
          <div className="flex items-center gap-4 mt-6 text-sm text-muted-foreground"><span>5 min read</span><span>•</span><span>Intermediate</span></div>
        </header>
        <div className="w-full h-80 bg-gradient-to-br from-pink-200 to-purple-300 rounded-3xl mb-12 flex items-center justify-center shadow-2xl"><span className="text-8xl">{config.emoji}</span></div>
        <div className="prose prose-lg max-w-none">
          <p className="text-xl leading-relaxed text-foreground/80 mb-8">{config.content}</p>
          <h2 className="text-3xl mt-12 mb-6 bg-gradient-to-r from-pink-600 to-purple-600 bg-clip-text text-transparent">Causes & Fixes</h2>
          <div className="space-y-6 my-8">
            {config.causes.map((c, i) => (
              <div key={i} className="bg-white rounded-2xl p-6 shadow-lg border-2 border-pink-200">
                <h3 className="text-xl mb-3">{c.title}</h3>
                <p className="text-sm text-muted-foreground mb-3">{c.body}</p>
                <div className="bg-green-50 rounded-lg p-3 text-xs text-green-800"><strong>Fix:</strong> {c.fix}</div>
              </div>
            ))}
          </div>
          <div className="bg-gradient-to-r from-pink-500 to-purple-600 text-white rounded-2xl p-8 my-12">
            <h2 className="text-3xl mb-4">Master Cake Baking Science</h2>
            <p className="text-lg text-white/90 mb-6">Browse all our cake science articles.</p>
            <Link to="/articles" className="inline-flex items-center gap-2 bg-white text-pink-600 px-6 py-3 rounded-lg hover:shadow-xl transition-all hover:scale-105">Browse Cake Science<ArrowLeft className="w-4 h-4 rotate-180" /></Link>
          </div>
        </div>
      </article>
      <Footer />
    </div>
  );
}
