/**
 * Library cards for phase-2 topic gap articles (time, temperature, sequence, holding).
 * Specs live in `src/app/data/newScienceArticles/phase2GapArticlesPart*.ts`.
 */
export const PHASE2_GAP_ARTICLE_CATALOG_ROWS = [
  {
    title: 'Why Cakes Oil Out (Fat Separation in Batter)',
    description: 'Emulsion timing, fat temperature, and mixing sequence decide whether oil beads later weep from the crumb.',
    category: 'Cake Science',
    readTime: '8 min read',
    color: 'from-pink-500 to-purple-600',
    url: '/cake-science/why-cakes-oil-out',
  },
  {
    title: 'Why Cakes Taste Flat (Flavor Layering Failure)',
    description: 'Maillard timing, salt, acid, and aromatic volatility stack—or cancel—depending on bake curve and cooling.',
    category: 'Cake Science',
    readTime: '8 min read',
    color: 'from-purple-500 to-rose-600',
    url: '/cake-science/why-cakes-taste-flat',
  },
  {
    title: 'Why Cakes Form a Thick Crust',
    description: 'Surface heat flux, sugar load, and bake time relative to pan size build a shell before the center finishes.',
    category: 'Cake Science',
    readTime: '7 min read',
    color: 'from-rose-500 to-pink-600',
    url: '/cake-science/why-cakes-form-a-thick-crust',
  },
  {
    title: 'Why Cakes Stick to Themselves When Layering',
    description: 'Surface tack from sugar glass, incomplete cool-down, and pressure during stacking.',
    category: 'Cake Science',
    readTime: '7 min read',
    color: 'from-fuchsia-500 to-purple-600',
    url: '/cake-science/why-cakes-stick-to-themselves-when-layering',
  },
  {
    title: 'Why Cakes Lose Height After Frosting',
    description: 'Compression, temperature shock, and moisture migration from frosting into a delicate crumb.',
    category: 'Cake Science',
    readTime: '8 min read',
    color: 'from-pink-500 to-rose-600',
    url: '/cake-science/why-cakes-lose-height-after-frosting',
  },
  {
    title: 'Why Pie Fillings Taste Bland (Flavor Dilution Problem)',
    description: 'Fruit water, thickener timing, and bake temperature dilute or trap volatile aromatics.',
    category: 'Pie Science',
    readTime: '8 min read',
    color: 'from-amber-600 to-orange-600',
    url: '/pie-science/why-pie-fillings-taste-bland',
  },
  {
    title: 'Why Fruit Pies Turn Grainy',
    description: 'Pectin breakdown, sugar crystallization, and overcooked thickeners change mouthfeel.',
    category: 'Pie Science',
    readTime: '7 min read',
    color: 'from-orange-500 to-amber-700',
    url: '/pie-science/why-fruit-pies-turn-grainy',
  },
  {
    title: 'Why Custard Pies Crack',
    description: 'Overbake sets egg proteins too tight; cooling shrinkage exceeds what the surface can flex.',
    category: 'Pie Science',
    readTime: '7 min read',
    color: 'from-yellow-600 to-orange-600',
    url: '/pie-science/why-custard-pies-crack',
  },
  {
    title: 'Why Pie Crust Blisters',
    description: 'Steam pockets under thin dough sheets before lamination-like layers set.',
    category: 'Pie Science',
    readTime: '6 min read',
    color: 'from-amber-500 to-yellow-700',
    url: '/pie-science/why-pie-crust-blisters',
  },
  {
    title: 'Why Double Crust Pies Trap Steam',
    description: 'A sealed lid raises internal pressure until vents or edge leaks become the only escape.',
    category: 'Pie Science',
    readTime: '8 min read',
    color: 'from-orange-600 to-red-600',
    url: '/pie-science/why-double-crust-pies-trap-steam',
  },
  {
    title: 'Why Ice Cream Tastes Too Sweet (Cold Suppression Curve)',
    description: 'Sweetness perception shifts with temperature; cold hides bitterness but can leave sucrose loud.',
    category: 'Ice Cream Science',
    readTime: '7 min read',
    color: 'from-cyan-500 to-blue-600',
    url: '/ice-cream-science/why-ice-cream-tastes-too-sweet',
  },
  {
    title: "Why Ice Cream Doesn't Scoop Smoothly",
    description:
      'Hardness is tied to freezing point depression, ice fraction, and temper time—not bad luck.',
    category: 'Ice Cream Science',
    readTime: '7 min read',
    color: 'from-sky-500 to-cyan-600',
    url: '/ice-cream-science/why-ice-cream-doesnt-scoop-smoothly',
  },
  {
    title: 'Why Ice Cream Loses Air (Overrun Collapse)',
    description: 'Dasher time, viscosity, and cold chain breaks determine how much air stays trapped.',
    category: 'Ice Cream Science',
    readTime: '8 min read',
    color: 'from-blue-500 to-indigo-600',
    url: '/ice-cream-science/why-ice-cream-loses-air-overrun-collapse',
  },
  {
    title: 'Why Ice Cream Develops Ice Layers Over Time',
    description: 'Temperature oscillation drives water vapor to refreeze at the coldest interface.',
    category: 'Ice Cream Science',
    readTime: '8 min read',
    color: 'from-cyan-600 to-blue-700',
    url: '/ice-cream-science/why-ice-cream-develops-ice-layers-over-time',
  },
  {
    title: 'Why Ice Cream Base Curdles Before Churning',
    description: 'Egg yolk + heat + acid without enough buffering crosses the tight curd line.',
    category: 'Ice Cream Science',
    readTime: '7 min read',
    color: 'from-teal-500 to-cyan-600',
    url: '/ice-cream-science/why-ice-cream-base-curdles-before-churning',
  },
  {
    title: 'Why Sauces Break When Reheated',
    description: 'Second-pass heat exceeds the emulsion’s stability window; fat coalesces and water weeps.',
    category: 'Sauce Science',
    readTime: '8 min read',
    color: 'from-rose-600 to-orange-600',
    url: '/sauce-science/why-sauces-break-when-reheated',
  },
  {
    title: 'Why Sauces Taste Good Hot but Flat Cold',
    description: 'Volatility, fat solidification, and salt perception shift with temperature and time off heat.',
    category: 'Sauce Science',
    readTime: '7 min read',
    color: 'from-orange-600 to-rose-600',
    url: '/sauce-science/why-sauces-taste-good-hot-but-flat-cold',
  },
  {
    title: 'Why Sauces Separate on the Plate (Holding Failure)',
    description: 'Carry time, plate heat, and oil-water relaxation undo what the pan achieved.',
    category: 'Sauce Science',
    readTime: '8 min read',
    color: 'from-red-600 to-orange-600',
    url: '/sauce-science/why-sauces-separate-on-the-plate',
  },
  {
    title: 'Why Sauces Taste Metallic',
    description: 'Reactive pans, long wine reduction, and certain spices release metal ions or perceptions.',
    category: 'Sauce Science',
    readTime: '7 min read',
    color: 'from-amber-700 to-rose-700',
    url: '/sauce-science/why-sauces-taste-metallic',
  },
  {
    title: 'Why Sauces Clash With Protein (Pairing Science)',
    description: 'Intensity, fat level, and Maillard spectrum need to align across the bite timeline.',
    category: 'Sauce Science',
    readTime: '8 min read',
    color: 'from-rose-700 to-orange-600',
    url: '/sauce-science/why-sauces-clash-with-protein',
  },
  {
    title: 'Why Bread Smells Yeasty (Fermentation Imbalance)',
    description: 'Fast ferment, warm bulk, and high yeast fraction spike esters before flavor matures.',
    category: 'Bread Science',
    readTime: '8 min read',
    color: 'from-amber-500 to-yellow-600',
    url: '/bread-science/why-bread-smells-yeasty',
  },
  {
    title: 'Why Bread Has No Flavor (Underdeveloped Fermentation)',
    description: 'Short autolyse, no preferment, and rush to oven starve complexity.',
    category: 'Bread Science',
    readTime: '8 min read',
    color: 'from-yellow-600 to-orange-500',
    url: '/bread-science/why-bread-has-no-flavor',
  },
  {
    title: 'Why Bread Crumb Is Too Tight (Cell Structure Failure)',
    description: 'Under-proofing, heavy degassing, or weak oven spring limit cell expansion.',
    category: 'Bread Science',
    readTime: '8 min read',
    color: 'from-orange-500 to-amber-700',
    url: '/bread-science/why-bread-crumb-is-too-tight',
  },
  {
    title: 'Why Bread Has Large Holes (Gas Coalescence)',
    description: 'Uneven bubble distribution merges into chambers when gluten films are uneven.',
    category: 'Bread Science',
    readTime: '7 min read',
    color: 'from-amber-600 to-yellow-700',
    url: '/bread-science/why-bread-has-large-holes',
  },
  {
    title: 'Why Bread Dough Tears Instead of Stretching',
    description: 'Under-hydrated gluten, cold fat, or insufficient rest limits extensibility.',
    category: 'Bread Science',
    readTime: '7 min read',
    color: 'from-yellow-500 to-amber-600',
    url: '/bread-science/why-bread-dough-tears-instead-of-stretching',
  },
  {
    title: 'Why Cookies Taste Floury',
    description: 'Raw starch perception when hydration, bake time, or mixing order leaves flour ungelatinized.',
    category: 'Cookie Science',
    readTime: '7 min read',
    color: 'from-amber-500 to-orange-600',
    url: '/cookie-science/why-cookies-taste-floury',
  },
  {
    title: 'Why Cookies Have No Depth of Flavor',
    description: 'Single-note sugar without Maillard contrast, salt, brown butter, or aged dough.',
    category: 'Cookie Science',
    readTime: '8 min read',
    color: 'from-orange-500 to-red-500',
    url: '/cookie-science/why-cookies-have-no-depth-of-flavor',
  },
  {
    title: 'Why Cookies Stick to Each Other After Baking',
    description: 'Edges stay thermoplastic until cooled; steam and sugar bridges fuse contact patches.',
    category: 'Cookie Science',
    readTime: '6 min read',
    color: 'from-yellow-500 to-amber-600',
    url: '/cookie-science/why-cookies-stick-to-each-other-after-baking',
  },
  {
    title: 'Why Cookies Puff Instead of Spread',
    description: 'Cold fat, high flour, strong leavening, and short bake set a dome before flow.',
    category: 'Cookie Science',
    readTime: '7 min read',
    color: 'from-amber-600 to-orange-700',
    url: '/cookie-science/why-cookies-puff-instead-of-spread',
  },
  {
    title: 'Why Cookies Taste Better the Next Day',
    description: 'Moisture equilibrates, volatiles mellow, and crystalline sugar textures shift.',
    category: 'Cookie Science',
    readTime: '7 min read',
    color: 'from-orange-600 to-amber-600',
    url: '/cookie-science/why-cookies-taste-better-the-next-day',
  },
  {
    title: 'Why Coffee Tastes Thin But Bitter (Split Extraction Problem)',
    description: 'Channeling and uneven wetting yield sour/weak zones and bitter zones in the same cup.',
    category: 'Coffee Science',
    readTime: '8 min read',
    color: 'from-stone-600 to-amber-800',
    url: '/coffee-science/why-coffee-tastes-thin-but-bitter',
  },
  {
    title: "Why Coffee Aroma Doesn't Match Taste",
    description: 'Volatiles dominate nose; dissolved solids dominate palate—temperature splits the experience.',
    category: 'Coffee Science',
    readTime: '7 min read',
    color: 'from-amber-800 to-stone-700',
    url: '/coffee-science/why-coffee-aroma-doesnt-match-taste',
  },
  {
    title: 'Why Coffee Tastes Better at Certain Temperatures',
    description: 'Sweet–sour–bitter balance moves as solubility and volatility change down the cooling curve.',
    category: 'Coffee Science',
    readTime: '8 min read',
    color: 'from-stone-700 to-amber-700',
    url: '/coffee-science/why-coffee-tastes-better-at-certain-temperatures',
  },
  {
    title: 'Why Coffee Water Chemistry Matters',
    description: 'Hardness, alkalinity, and filter solids change extraction efficiency and sensory balance.',
    category: 'Coffee Science',
    readTime: '8 min read',
    color: 'from-amber-700 to-yellow-700',
    url: '/coffee-science/why-coffee-water-chemistry-matters',
  },
  {
    title: 'Why Espresso Channels (Extraction Path Failure)',
    description: 'Density gradients, edge effects, and uneven prep create least-resistance rivers.',
    category: 'Coffee Science',
    readTime: '8 min read',
    color: 'from-stone-800 to-amber-900',
    url: '/coffee-science/why-espresso-channels',
  },
];
