export interface PercentRange {
  min: number;
  max: number;
}

export interface BreadType {
  id: string;
  name: string;
  emoji: string;
  category: string;
  hydrationRange: PercentRange;
  fatRange: PercentRange;
  sugarRange: PercentRange;
  processStyle: string;
  fermentationTime: string;
  textureOutput: string;
  crust: string;
  bestFor: string;
  description: string;
  scienceNote: string;
  characteristics: string[];
  color: string;
  baseFormula: { name: string; amount: number }[];
  recipes: BreadRecipe[];
}

export interface BreadRecipe {
  name: string;
  emoji: string;
  description: string;
  group?: string;
  ingredients: { name: string; amount: number }[];
}

export const breadTypes: BreadType[] = [
  {
    id: 'lean-white',
    name: 'Lean White',
    emoji: '🍞',
    category: 'Lean',
    hydrationRange: { min: 60, max: 65 },
    fatRange: { min: 0, max: 0 },
    sugarRange: { min: 0, max: 2 },
    processStyle: 'Knead',
    fermentationTime: 'Short',
    textureOutput: 'Soft, even crumb',
    crust: 'Light',
    bestFor: 'Everyday loaves, beginners, and clean wheat flavor.',
    description: 'Simple flour, water, salt, and yeast — high gluten development from kneading, modest hydration.',
    scienceNote: 'Low fat and sugar let gluten form clearly; short bulk keeps flavor mild and crumb even.',
    characteristics: ['Neutral', 'Versatile', 'Knead-forward'],
    color: 'from-amber-200 to-yellow-300',
    baseFormula: [
      { name: 'Bread Flour', amount: 500 },
      { name: 'Water', amount: 315 },
      { name: 'Salt', amount: 10 },
      { name: 'Instant Yeast', amount: 5 },
    ],
    recipes: [
      {
        group: 'Straight dough',
        name: 'Same-Day Lean Loaf',
        emoji: '🍞',
        description: 'Single rise after knead; good same-day loaf.',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Water', amount: 312 },
          { name: 'Salt', amount: 10 },
          { name: 'Instant Yeast', amount: 5 },
        ],
      },
      {
        group: 'Straight dough',
        name: 'Touch of Sugar (1%)',
        emoji: '🥄',
        description: 'A little sugar feeds yeast and browns the crust slightly.',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Water', amount: 310 },
          { name: 'Salt', amount: 10 },
          { name: 'Granulated Sugar', amount: 5 },
          { name: 'Instant Yeast', amount: 5 },
        ],
      },
    ],
  },
  {
    id: 'artisan',
    name: 'Artisan',
    emoji: '🥖',
    category: 'High hydration',
    hydrationRange: { min: 70, max: 80 },
    fatRange: { min: 0, max: 0 },
    sugarRange: { min: 0, max: 0 },
    processStyle: 'No-knead / stretch',
    fermentationTime: 'Long',
    textureOutput: 'Open, airy holes',
    crust: 'Thick',
    bestFor: 'Rustic boules, overnight schedules, dramatic crumb.',
    description: 'Wet dough, time replaces heavy kneading; stretch-and-folds build structure gently.',
    scienceNote: 'Long autolyse and fermentation develop flavor; high water limits tight gluten sheets so holes stay open.',
    characteristics: ['Wet dough', 'Time', 'Open crumb'],
    color: 'from-orange-200 to-amber-400',
    baseFormula: [
      { name: 'Bread Flour', amount: 500 },
      { name: 'Water', amount: 375 },
      { name: 'Salt', amount: 10 },
      { name: 'Instant Yeast', amount: 2 },
    ],
    recipes: [
      {
        group: 'No-knead',
        name: 'Overnight No-Knead',
        emoji: '🌙',
        description: 'Minimal mixing, long cold or room ferment, bake in Dutch oven.',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Water', amount: 375 },
          { name: 'Salt', amount: 10 },
          { name: 'Instant Yeast', amount: 1.5 },
        ],
      },
      {
        group: 'Stretch & fold',
        name: 'Same-Day High Hydration',
        emoji: '🌀',
        description: 'Warm bulk with folds every 30 minutes.',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Water', amount: 360 },
          { name: 'Salt', amount: 10 },
          { name: 'Instant Yeast', amount: 3 },
        ],
      },
    ],
  },
  {
    id: 'sourdough',
    name: 'Sourdough',
    emoji: '🫓',
    category: 'Preferment',
    hydrationRange: { min: 65, max: 75 },
    fatRange: { min: 0, max: 0 },
    sugarRange: { min: 0, max: 0 },
    processStyle: 'Fold + ferment',
    fermentationTime: 'Very long',
    textureOutput: 'Chewy, irregular',
    crust: 'Thick',
    bestFor: 'Wild yeast flavor, chewy crumb, serious scheduling.',
    description: 'Acidic culture and long builds create complex flavor and a sturdy, chewy matrix.',
    scienceNote: 'Organic acids strengthen gluten differently than commercial yeast alone; folds align dough without aggressive kneading.',
    characteristics: ['Tangy', 'Chewy', 'Long timeline'],
    color: 'from-stone-300 to-amber-700',
    baseFormula: [
      { name: 'Bread Flour', amount: 500 },
      { name: 'Water', amount: 350 },
      { name: 'Salt', amount: 10 },
      { name: 'Instant Yeast', amount: 1 },
    ],
    recipes: [
      {
        group: 'Yeast-assisted sourdough-style',
        name: 'Long Ferment Lean (yeast)',
        emoji: '⏳',
        description: 'Mimics sourdough timeline with a tiny yeast pinch; swap in ripe levain for real sourdough.',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Water', amount: 340 },
          { name: 'Salt', amount: 10 },
          { name: 'Instant Yeast', amount: 1 },
        ],
      },
      {
        group: 'Fold schedule',
        name: 'Weekend Sourdough-Style Build',
        emoji: '📅',
        description: 'Cool bulk, multiple coil or letter folds, overnight proof.',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Water', amount: 360 },
          { name: 'Salt', amount: 11 },
          { name: 'Instant Yeast', amount: 0.5 },
        ],
      },
    ],
  },
  {
    id: 'sandwich',
    name: 'Sandwich Bread',
    emoji: '🥪',
    category: 'Enriched lean',
    hydrationRange: { min: 60, max: 65 },
    fatRange: { min: 5, max: 10 },
    sugarRange: { min: 5, max: 10 },
    processStyle: 'Knead',
    fermentationTime: 'Medium',
    textureOutput: 'Fine, soft, uniform',
    crust: 'Thin',
    bestFor: 'Pullman pans, toast, kid-friendly slices.',
    description: 'Fat and sugar tenderize and soften crust; kneading yields a tight, even crumb.',
    scienceNote: 'Sugar retains moisture; fat shortens gluten strands for tenderness.',
    characteristics: ['Soft', 'Uniform', 'Pan loaf'],
    color: 'from-yellow-100 to-amber-200',
    baseFormula: [
      { name: 'Bread Flour', amount: 500 },
      { name: 'Water', amount: 310 },
      { name: 'Whole Milk', amount: 40 },
      { name: 'Unsalted Butter', amount: 35 },
      { name: 'Granulated Sugar', amount: 35 },
      { name: 'Salt', amount: 9 },
      { name: 'Instant Yeast', amount: 7 },
    ],
    recipes: [
      {
        group: 'Pan loaf',
        name: 'Classic Pullman-Style',
        emoji: '📦',
        description: 'Milk + butter + sugar for a tight, soft crumb.',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Water', amount: 280 },
          { name: 'Whole Milk', amount: 50 },
          { name: 'Unsalted Butter', amount: 40 },
          { name: 'Granulated Sugar', amount: 40 },
          { name: 'Salt', amount: 9 },
          { name: 'Instant Yeast', amount: 7 },
        ],
      },
      {
        group: 'Pan loaf',
        name: 'Softer Crumb (higher enrich)',
        emoji: '🧈',
        description: 'Toward the top of fat/sugar range for pillowy slices.',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Water', amount: 270 },
          { name: 'Whole Milk', amount: 60 },
          { name: 'Unsalted Butter', amount: 48 },
          { name: 'Granulated Sugar', amount: 45 },
          { name: 'Salt', amount: 8 },
          { name: 'Instant Yeast', amount: 8 },
        ],
      },
    ],
  },
  {
    id: 'brioche',
    name: 'Brioche',
    emoji: '🥐',
    category: 'Rich',
    hydrationRange: { min: 50, max: 60 },
    fatRange: { min: 30, max: 50 },
    sugarRange: { min: 10, max: 20 },
    processStyle: 'Intensive knead',
    fermentationTime: 'Medium',
    textureOutput: 'Rich, fluffy, cake-like',
    crust: 'Soft',
    bestFor: 'Buns, babka, French toast.',
    description: 'Lots of butter and egg; intensive mixing builds an elastic, enriched network.',
    scienceNote: 'Fat coats flour early if added wrong — brioche usually develops gluten first, then works in butter gradually.',
    characteristics: ['Rich', 'Egg-forward', 'Tender'],
    color: 'from-rose-200 to-amber-300',
    baseFormula: [
      { name: 'Bread Flour', amount: 500 },
      { name: 'Whole Egg (large)', amount: 250 },
      { name: 'Water', amount: 120 },
      { name: 'Unsalted Butter', amount: 200 },
      { name: 'Granulated Sugar', amount: 75 },
      { name: 'Salt', amount: 8 },
      { name: 'Instant Yeast', amount: 10 },
    ],
    recipes: [
      {
        group: 'Classic',
        name: 'Classic Brioche (≈40% butter)',
        emoji: '✨',
        description: 'Benchmark rich dough; long mix, cool butter in stages.',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Whole Egg (large)', amount: 250 },
          { name: 'Water', amount: 100 },
          { name: 'Unsalted Butter', amount: 200 },
          { name: 'Granulated Sugar', amount: 80 },
          { name: 'Salt', amount: 8 },
          { name: 'Instant Yeast', amount: 10 },
        ],
      },
      {
        group: 'Classic',
        name: 'Extra-Rich (≈45% butter)',
        emoji: '👑',
        description: 'Push fat toward the high end; handle cold, rest often.',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Whole Egg (large)', amount: 275 },
          { name: 'Water', amount: 80 },
          { name: 'Unsalted Butter', amount: 225 },
          { name: 'Granulated Sugar', amount: 90 },
          { name: 'Salt', amount: 8 },
          { name: 'Instant Yeast', amount: 11 },
        ],
      },
    ],
  },
  {
    id: 'focaccia',
    name: 'Focaccia',
    emoji: '🫒',
    category: 'Flatbread',
    hydrationRange: { min: 75, max: 85 },
    fatRange: { min: 10, max: 20 },
    sugarRange: { min: 0, max: 5 },
    processStyle: 'Minimal handling',
    fermentationTime: 'Medium',
    textureOutput: 'Very airy, oily',
    crust: 'Crisp',
    bestFor: 'Sheet pans, dimples, olive oil pools.',
    description: 'High water, generous oil in the pan; gentle stretching preserves bubbles.',
    scienceNote: 'Oil fries the bottom while steam opens the interior; sugar is optional for browning.',
    characteristics: ['Olive oil', 'Dimpled', 'Wet dough'],
    color: 'from-lime-100 to-emerald-300',
    baseFormula: [
      { name: 'Bread Flour', amount: 500 },
      { name: 'Water', amount: 400 },
      { name: 'Olive Oil', amount: 60 },
      { name: 'Salt', amount: 10 },
      { name: 'Instant Yeast', amount: 4 },
    ],
    recipes: [
      {
        group: 'Sheet',
        name: 'Pool of Oil Focaccia',
        emoji: '🛢️',
        description: 'Oil in the pan is part of the structure and flavor.',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Water', amount: 400 },
          { name: 'Olive Oil', amount: 70 },
          { name: 'Salt', amount: 10 },
          { name: 'Instant Yeast', amount: 4 },
        ],
      },
      {
        group: 'Sheet',
        name: 'Hint of Sugar for Color',
        emoji: '🌾',
        description: 'Tiny sugar helps crust color without sweetness.',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Water', amount: 390 },
          { name: 'Olive Oil', amount: 65 },
          { name: 'Granulated Sugar', amount: 8 },
          { name: 'Salt', amount: 10 },
          { name: 'Instant Yeast', amount: 4 },
        ],
      },
    ],
  },
  {
    id: 'ciabatta',
    name: 'Ciabatta',
    emoji: '🇮🇹',
    category: 'High hydration',
    hydrationRange: { min: 75, max: 85 },
    fatRange: { min: 0, max: 0 },
    sugarRange: { min: 0, max: 0 },
    processStyle: 'Gentle folds',
    fermentationTime: 'Long',
    textureOutput: 'Large holes, chewy',
    crust: 'Crisp',
    bestFor: 'Sandwiches, dipping, wet dough practice.',
    description: 'Extremely wet dough, stretchy gluten from folds, no fat to shorten crumb.',
    scienceNote: 'High hydration limits CO₂ escape paths — bubbles coalesce into irregular pockets.',
    characteristics: ['Wet', 'Chewy', 'Lean'],
    color: 'from-sky-100 to-indigo-200',
    baseFormula: [
      { name: 'Bread Flour', amount: 500 },
      { name: 'Water', amount: 400 },
      { name: 'Salt', amount: 10 },
      { name: 'Instant Yeast', amount: 3 },
    ],
    recipes: [
      {
        group: 'Wet dough',
        name: '80% Hydration Ciabatta',
        emoji: '💧',
        description: 'Benchmark wet dough; handle with a bench scraper.',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Water', amount: 400 },
          { name: 'Salt', amount: 10 },
          { name: 'Instant Yeast', amount: 3 },
        ],
      },
      {
        group: 'Wet dough',
        name: 'Biga-Style (optional overnight)',
        emoji: '🌅',
        description: 'Slightly lower yeast, longer flavor build (simulate with cold water).',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Water', amount: 385 },
          { name: 'Salt', amount: 11 },
          { name: 'Instant Yeast', amount: 2 },
        ],
      },
    ],
  },
  {
    id: 'bagel',
    name: 'Bagels',
    emoji: '🥯',
    category: 'Boiled',
    hydrationRange: { min: 50, max: 55 },
    fatRange: { min: 0, max: 0 },
    sugarRange: { min: 0, max: 3 },
    processStyle: 'Knead + boil',
    fermentationTime: 'Short',
    textureOutput: 'Dense, tight',
    crust: 'Chewy',
    bestFor: 'Chewy rounds, malt bath, toppings.',
    description: 'Stiff dough, boil sets crust before bake; optional barley malt in water.',
    scienceNote: 'Low hydration and boiling gelatinize starch for that signature chew.',
    characteristics: ['Stiff', 'Chewy', 'Boiled'],
    color: 'from-amber-300 to-orange-400',
    baseFormula: [
      { name: 'Bread Flour', amount: 500 },
      { name: 'Water', amount: 265 },
      { name: 'Granulated Sugar', amount: 10 },
      { name: 'Salt', amount: 10 },
      { name: 'Instant Yeast', amount: 5 },
    ],
    recipes: [
      {
        group: 'Classic',
        name: 'NY-Style Stiff Dough',
        emoji: '🗽',
        description: 'Dense crumb; retard for flavor if you have time.',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Water', amount: 260 },
          { name: 'Granulated Sugar', amount: 12 },
          { name: 'Salt', amount: 10 },
          { name: 'Instant Yeast', amount: 5 },
        ],
      },
      {
        group: 'Classic',
        name: 'Lean Bagel (no sugar in dough)',
        emoji: '⚪',
        description: 'Sugar only in the boil if desired.',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Water', amount: 268 },
          { name: 'Salt', amount: 10 },
          { name: 'Instant Yeast', amount: 5 },
        ],
      },
    ],
  },
  {
    id: 'pizza',
    name: 'Pizza Dough',
    emoji: '🍕',
    category: 'Flatbread',
    hydrationRange: { min: 60, max: 70 },
    fatRange: { min: 2, max: 5 },
    sugarRange: { min: 0, max: 2 },
    processStyle: 'Knead / cold ferment',
    fermentationTime: 'Medium–long',
    textureOutput: 'Stretchy, light',
    crust: 'Crisp',
    bestFor: 'Neapolitan-style (adjust bake), NY slice, home oven steel.',
    description: 'Moderate hydration, small oil for extensibility; time in the fridge develops flavor.',
    scienceNote: 'Cold fermentation increases extensibility and aroma compounds without much sugar.',
    characteristics: ['Stretchy', 'Steel/stone', 'Optional cold proof'],
    color: 'from-red-200 to-orange-300',
    baseFormula: [
      { name: 'Bread Flour', amount: 500 },
      { name: 'Water', amount: 325 },
      { name: 'Olive Oil', amount: 15 },
      { name: 'Salt', amount: 10 },
      { name: 'Instant Yeast', amount: 3 },
    ],
    recipes: [
      {
        group: 'Same day',
        name: 'Same-Day Pizza',
        emoji: '🔥',
        description: 'Oil for tenderness; short ferment.',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Water', amount: 320 },
          { name: 'Olive Oil', amount: 18 },
          { name: 'Salt', amount: 10 },
          { name: 'Instant Yeast', amount: 4 },
        ],
      },
      {
        group: 'Cold ferment',
        name: '3-Day Cold Dough',
        emoji: '❄️',
        description: 'Low yeast, long fridge; tiny sugar optional.',
        ingredients: [
          { name: 'Bread Flour', amount: 500 },
          { name: 'Water', amount: 330 },
          { name: 'Olive Oil', amount: 12 },
          { name: 'Granulated Sugar', amount: 5 },
          { name: 'Salt', amount: 12 },
          { name: 'Instant Yeast', amount: 1 },
        ],
      },
    ],
  },
  {
    id: 'whole-wheat',
    name: 'Whole Wheat',
    emoji: '🌾',
    category: 'Hearty',
    hydrationRange: { min: 65, max: 75 },
    fatRange: { min: 0, max: 5 },
    sugarRange: { min: 0, max: 5 },
    processStyle: 'Knead',
    fermentationTime: 'Medium',
    textureOutput: 'Dense, hearty',
    crust: 'Medium',
    bestFor: 'Sandwiches, toast, fiber-forward meals.',
    description: 'Bran cuts gluten strands; higher hydration and rest help counter dryness.',
    scienceNote: 'Pentosans in bran absorb more water — doughs often need extra time and liquid vs white flour.',
    characteristics: ['Hearty', 'Flecked crumb', 'Nutty'],
    color: 'from-amber-700 to-yellow-900',
    baseFormula: [
      { name: 'Whole Wheat Flour', amount: 500 },
      { name: 'Water', amount: 350 },
      { name: 'Olive Oil', amount: 15 },
      { name: 'Salt', amount: 10 },
      { name: 'Honey', amount: 15 },
      { name: 'Instant Yeast', amount: 6 },
    ],
    recipes: [
      {
        group: '100% whole grain',
        name: 'Hearty 100% WW',
        emoji: '💪',
        description: 'Oil and honey for tenderness and moisture.',
        ingredients: [
          { name: 'Whole Wheat Flour', amount: 500 },
          { name: 'Water', amount: 360 },
          { name: 'Olive Oil', amount: 18 },
          { name: 'Honey', amount: 18 },
          { name: 'Salt', amount: 10 },
          { name: 'Instant Yeast', amount: 6 },
        ],
      },
      {
        group: 'Blend',
        name: '70% WW / 30% Bread',
        emoji: '🔀',
        description: 'Easier rise with some strong white flour.',
        ingredients: [
          { name: 'Whole Wheat Flour', amount: 350 },
          { name: 'Bread Flour', amount: 150 },
          { name: 'Water', amount: 340 },
          { name: 'Olive Oil', amount: 12 },
          { name: 'Salt', amount: 10 },
          { name: 'Instant Yeast', amount: 6 },
        ],
      },
    ],
  },
];
