// AUTO-GENERATED by scripts/generate-science-article-pages.ts — do not edit by hand
import WhyBreadDoesntRise from "./pages/WhyBreadDoesntRise";
import WhyBreadIsDense from "./pages/WhyBreadIsDense";
import WhyBreadIsGummyInside from "./pages/WhyBreadIsGummyInside";
import WhyBreadCollapsesAfterBaking from "./pages/WhyBreadCollapsesAfterBaking";
import WhyBreadIsDry from "./pages/WhyBreadIsDry";
import WhyBreadIsTooChewy from "./pages/WhyBreadIsTooChewy";
import WhyBreadCrustIsTooHard from "./pages/WhyBreadCrustIsTooHard";
import WhyBreadCrustIsTooSoft from "./pages/WhyBreadCrustIsTooSoft";
import WhyBreadBurnsOnTheBottom from "./pages/WhyBreadBurnsOnTheBottom";
import WhyBreadIsPale from "./pages/WhyBreadIsPale";
import WhyDoughIsTooSticky from "./pages/WhyDoughIsTooSticky";
import WhyDoughWontHoldShape from "./pages/WhyDoughWontHoldShape";
import WhyDoughSpringsBackWhenShaping from "./pages/WhyDoughSpringsBackWhenShaping";
import WhyDoughRisesTooFast from "./pages/WhyDoughRisesTooFast";
import WhyDoughRisesTooSlow from "./pages/WhyDoughRisesTooSlow";
import WhyBreadNeedsSteam from "./pages/WhyBreadNeedsSteam";
import WhyOvenSpringHappens from "./pages/WhyOvenSpringHappens";
import WhyBreadNeedsScoring from "./pages/WhyBreadNeedsScoring";
import BreadFlourVsAllPurposeFlour from "./pages/BreadFlourVsAllPurposeFlour";
import WhyHydrationMattersInBread from "./pages/WhyHydrationMattersInBread";
import WhyCookiesTasteTooSweet from "./pages/WhyCookiesTasteTooSweet";
import WhyCookiesSpreadInOvenButNotBefore from "./pages/WhyCookiesSpreadInOvenButNotBefore";
import WhyCookiesTurnOutDifferentEachBatch from "./pages/WhyCookiesTurnOutDifferentEachBatch";
import WhyChillingCookieDoughMatters from "./pages/WhyChillingCookieDoughMatters";
import WhyCookiesStickTogether from "./pages/WhyCookiesStickTogether";
import WhyPieCrustCracksWhenRolling from "./pages/WhyPieCrustCracksWhenRolling";
import WhyPieCrustFallsApart from "./pages/WhyPieCrustFallsApart";
import WhyPieFillingBubblesOver from "./pages/WhyPieFillingBubblesOver";
import WhyPieCrustIsTooPale from "./pages/WhyPieCrustIsTooPale";
import WhyPieCrustBurnsBeforeFillingCooks from "./pages/WhyPieCrustBurnsBeforeFillingCooks";
import WhyCakesStickToPansEvenWhenGreased from "./pages/WhyCakesStickToPansEvenWhenGreased";
import WhyCakesBakeUnevenly from "./pages/WhyCakesBakeUnevenly";
import WhyCakesHaveAWetLayerAtTheBottom from "./pages/WhyCakesHaveAWetLayerAtTheBottom";
import WhyCakesTurnOutFlat from "./pages/WhyCakesTurnOutFlat";
import WhyCakesTasteEggy from "./pages/WhyCakesTasteEggy";
import WhyCakesAreTooSweet from "./pages/WhyCakesAreTooSweet";
import WhyCakesCrumbleWhenCut from "./pages/WhyCakesCrumbleWhenCut";
import WhyCakesStickToKnifeWhenCutting from "./pages/WhyCakesStickToKnifeWhenCutting";
import WhyCakesDryOutAfterOneDay from "./pages/WhyCakesDryOutAfterOneDay";
import WhyCakesSinkAroundTheEdges from "./pages/WhyCakesSinkAroundTheEdges";
import WhyCoffeeTastesHollow from "./pages/WhyCoffeeTastesHollow";
import WhyCoffeeTastesOverExtracted from "./pages/WhyCoffeeTastesOverExtracted";
import WhyCoffeeTastesUnderExtracted from "./pages/WhyCoffeeTastesUnderExtracted";
import WhyCoffeeStrengthVsExtractionMatters from "./pages/WhyCoffeeStrengthVsExtractionMatters";
import WhyCoffeeTastesDifferentEveryBrew from "./pages/WhyCoffeeTastesDifferentEveryBrew";
import WhyIceCreamIsTooHard from "./pages/WhyIceCreamIsTooHard";
import WhyIceCreamIsTooSoft from "./pages/WhyIceCreamIsTooSoft";
import WhyIceCreamTastesIcy from "./pages/WhyIceCreamTastesIcy";
import WhyIceCreamLacksFlavor from "./pages/WhyIceCreamLacksFlavor";
import WhyIceCreamSeparates from "./pages/WhyIceCreamSeparates";
import TemperatureSilentKillerSauces from "./pages/TemperatureSilentKillerSauces";
import OrderOfOperationsSauceTiming from "./pages/OrderOfOperationsSauceTiming";
import SaltAsAmplifierNotOnlySalty from "./pages/SaltAsAmplifierNotOnlySalty";
import WaterContentHiddenDilution from "./pages/WaterContentHiddenDilution";
import EmulsionVsNonEmulsionSauces from "./pages/EmulsionVsNonEmulsionSauces";
import ReductionCurveNonlinearFlavor from "./pages/ReductionCurveNonlinearFlavor";
import OneChangeRuleSauceDebugging from "./pages/OneChangeRuleSauceDebugging";
import UmamiAxisBeyondSaltAcidFatSweet from "./pages/UmamiAxisBeyondSaltAcidFatSweet";
import BrownGravyStockBased from "./pages/BrownGravyStockBased";
import WhiteGravySouthern from "./pages/WhiteGravySouthern";
import LemonPanSauce from "./pages/LemonPanSauce";
import MustardPanSauce from "./pages/MustardPanSauce";
import MushroomCreamSauce from "./pages/MushroomCreamSauce";
import SweetTomatoSauce from "./pages/SweetTomatoSauce";
import SpicyTomatoSauce from "./pages/SpicyTomatoSauce";
import BalsamicGlaze from "./pages/BalsamicGlaze";
import StockReductionDemi from "./pages/StockReductionDemi";
import TeriyakiGlaze from "./pages/TeriyakiGlaze";
import GarlicSoySauce from "./pages/GarlicSoySauce";
import NachoCheeseSauce from "./pages/NachoCheeseSauce";
import MornaySauce from "./pages/MornaySauce";
import BasilPesto from "./pages/BasilPesto";
import WhyCakesOilOut from "./pages/WhyCakesOilOut";
import WhyCakesTasteFlat from "./pages/WhyCakesTasteFlat";
import WhyCakesFormAThickCrust from "./pages/WhyCakesFormAThickCrust";
import WhyCakesStickToThemselvesWhenLayering from "./pages/WhyCakesStickToThemselvesWhenLayering";
import WhyCakesLoseHeightAfterFrosting from "./pages/WhyCakesLoseHeightAfterFrosting";
import WhyPieFillingsTasteBland from "./pages/WhyPieFillingsTasteBland";
import WhyFruitPiesTurnGrainy from "./pages/WhyFruitPiesTurnGrainy";
import WhyCustardPiesCrack from "./pages/WhyCustardPiesCrack";
import WhyPieCrustBlisters from "./pages/WhyPieCrustBlisters";
import WhyDoubleCrustPiesTrapSteam from "./pages/WhyDoubleCrustPiesTrapSteam";
import WhyIceCreamTastesTooSweet from "./pages/WhyIceCreamTastesTooSweet";
import WhyIceCreamDoesntScoopSmoothly from "./pages/WhyIceCreamDoesntScoopSmoothly";
import WhyIceCreamLosesAirOverrunCollapse from "./pages/WhyIceCreamLosesAirOverrunCollapse";
import WhyIceCreamDevelopsIceLayersOverTime from "./pages/WhyIceCreamDevelopsIceLayersOverTime";
import WhyIceCreamBaseCurdlesBeforeChurning from "./pages/WhyIceCreamBaseCurdlesBeforeChurning";
import WhySaucesBreakWhenReheated from "./pages/WhySaucesBreakWhenReheated";
import WhySaucesTasteGoodHotButFlatCold from "./pages/WhySaucesTasteGoodHotButFlatCold";
import WhySaucesSeparateOnThePlate from "./pages/WhySaucesSeparateOnThePlate";
import WhySaucesTasteMetallic from "./pages/WhySaucesTasteMetallic";
import WhySaucesClashWithProtein from "./pages/WhySaucesClashWithProtein";
import WhyBreadSmellsYeasty from "./pages/WhyBreadSmellsYeasty";
import WhyBreadHasNoFlavor from "./pages/WhyBreadHasNoFlavor";
import WhyBreadCrumbIsTooTight from "./pages/WhyBreadCrumbIsTooTight";
import WhyBreadHasLargeHoles from "./pages/WhyBreadHasLargeHoles";
import WhyBreadDoughTearsInsteadOfStretching from "./pages/WhyBreadDoughTearsInsteadOfStretching";
import WhyCookiesTasteFloury from "./pages/WhyCookiesTasteFloury";
import WhyCookiesHaveNoDepthOfFlavor from "./pages/WhyCookiesHaveNoDepthOfFlavor";
import WhyCookiesStickToEachOtherAfterBaking from "./pages/WhyCookiesStickToEachOtherAfterBaking";
import WhyCookiesPuffInsteadOfSpread from "./pages/WhyCookiesPuffInsteadOfSpread";
import WhyCookiesTasteBetterTheNextDay from "./pages/WhyCookiesTasteBetterTheNextDay";
import WhyCoffeeTastesThinButBitter from "./pages/WhyCoffeeTastesThinButBitter";
import WhyCoffeeAromaDoesntMatchTaste from "./pages/WhyCoffeeAromaDoesntMatchTaste";
import WhyCoffeeTastesBetterAtCertainTemperatures from "./pages/WhyCoffeeTastesBetterAtCertainTemperatures";
import WhyCoffeeWaterChemistryMatters from "./pages/WhyCoffeeWaterChemistryMatters";
import WhyEspressoChannels from "./pages/WhyEspressoChannels";

export const generatedNewScienceArticleRoutes = [
  { path: "bread-science/why-bread-doesnt-rise", Component: WhyBreadDoesntRise },
  { path: "bread-science/why-bread-is-dense", Component: WhyBreadIsDense },
  { path: "bread-science/why-bread-is-gummy-inside", Component: WhyBreadIsGummyInside },
  { path: "bread-science/why-bread-collapses-after-baking", Component: WhyBreadCollapsesAfterBaking },
  { path: "bread-science/why-bread-is-dry", Component: WhyBreadIsDry },
  { path: "bread-science/why-bread-is-too-chewy", Component: WhyBreadIsTooChewy },
  { path: "bread-science/why-bread-crust-is-too-hard", Component: WhyBreadCrustIsTooHard },
  { path: "bread-science/why-bread-crust-is-too-soft", Component: WhyBreadCrustIsTooSoft },
  { path: "bread-science/why-bread-burns-on-the-bottom", Component: WhyBreadBurnsOnTheBottom },
  { path: "bread-science/why-bread-is-pale", Component: WhyBreadIsPale },
  { path: "bread-science/why-dough-is-too-sticky", Component: WhyDoughIsTooSticky },
  { path: "bread-science/why-dough-wont-hold-shape", Component: WhyDoughWontHoldShape },
  { path: "bread-science/why-dough-springs-back-when-shaping", Component: WhyDoughSpringsBackWhenShaping },
  { path: "bread-science/why-dough-rises-too-fast", Component: WhyDoughRisesTooFast },
  { path: "bread-science/why-dough-rises-too-slow", Component: WhyDoughRisesTooSlow },
  { path: "bread-science/why-bread-needs-steam", Component: WhyBreadNeedsSteam },
  { path: "bread-science/why-oven-spring-happens", Component: WhyOvenSpringHappens },
  { path: "bread-science/why-bread-needs-scoring", Component: WhyBreadNeedsScoring },
  { path: "bread-science/bread-flour-vs-all-purpose-flour", Component: BreadFlourVsAllPurposeFlour },
  { path: "bread-science/why-hydration-matters-in-bread", Component: WhyHydrationMattersInBread },
  { path: "cookie-science/why-cookies-taste-too-sweet", Component: WhyCookiesTasteTooSweet },
  { path: "cookie-science/why-cookies-spread-in-oven-but-not-before", Component: WhyCookiesSpreadInOvenButNotBefore },
  { path: "cookie-science/why-cookies-turn-out-different-each-batch", Component: WhyCookiesTurnOutDifferentEachBatch },
  { path: "cookie-science/why-chilling-cookie-dough-matters", Component: WhyChillingCookieDoughMatters },
  { path: "cookie-science/why-cookies-stick-together", Component: WhyCookiesStickTogether },
  { path: "pie-science/why-pie-crust-cracks-when-rolling", Component: WhyPieCrustCracksWhenRolling },
  { path: "pie-science/why-pie-crust-falls-apart", Component: WhyPieCrustFallsApart },
  { path: "pie-science/why-pie-filling-bubbles-over", Component: WhyPieFillingBubblesOver },
  { path: "pie-science/why-pie-crust-is-too-pale", Component: WhyPieCrustIsTooPale },
  { path: "pie-science/why-pie-crust-burns-before-filling-cooks", Component: WhyPieCrustBurnsBeforeFillingCooks },
  { path: "cake-science/why-cakes-stick-to-pans-even-when-greased", Component: WhyCakesStickToPansEvenWhenGreased },
  { path: "cake-science/why-cakes-bake-unevenly", Component: WhyCakesBakeUnevenly },
  { path: "cake-science/why-cakes-have-a-wet-layer-at-the-bottom", Component: WhyCakesHaveAWetLayerAtTheBottom },
  { path: "cake-science/why-cakes-turn-out-flat", Component: WhyCakesTurnOutFlat },
  { path: "cake-science/why-cakes-taste-eggy", Component: WhyCakesTasteEggy },
  { path: "cake-science/why-cakes-are-too-sweet", Component: WhyCakesAreTooSweet },
  { path: "cake-science/why-cakes-crumble-when-cut", Component: WhyCakesCrumbleWhenCut },
  { path: "cake-science/why-cakes-stick-to-knife-when-cutting", Component: WhyCakesStickToKnifeWhenCutting },
  { path: "cake-science/why-cakes-dry-out-after-one-day", Component: WhyCakesDryOutAfterOneDay },
  { path: "cake-science/why-cakes-sink-around-the-edges", Component: WhyCakesSinkAroundTheEdges },
  { path: "coffee-science/why-coffee-tastes-hollow", Component: WhyCoffeeTastesHollow },
  { path: "coffee-science/why-coffee-tastes-over-extracted", Component: WhyCoffeeTastesOverExtracted },
  { path: "coffee-science/why-coffee-tastes-under-extracted", Component: WhyCoffeeTastesUnderExtracted },
  { path: "coffee-science/why-coffee-strength-vs-extraction-matters", Component: WhyCoffeeStrengthVsExtractionMatters },
  { path: "coffee-science/why-coffee-tastes-different-every-brew", Component: WhyCoffeeTastesDifferentEveryBrew },
  { path: "ice-cream-science/why-ice-cream-is-too-hard", Component: WhyIceCreamIsTooHard },
  { path: "ice-cream-science/why-ice-cream-is-too-soft", Component: WhyIceCreamIsTooSoft },
  { path: "ice-cream-science/why-ice-cream-tastes-icy", Component: WhyIceCreamTastesIcy },
  { path: "ice-cream-science/why-ice-cream-lacks-flavor", Component: WhyIceCreamLacksFlavor },
  { path: "ice-cream-science/why-ice-cream-separates", Component: WhyIceCreamSeparates },
  { path: "sauce-science/temperature-silent-killer-sauces", Component: TemperatureSilentKillerSauces },
  { path: "sauce-science/order-of-operations-sauce-timing", Component: OrderOfOperationsSauceTiming },
  { path: "sauce-science/salt-as-amplifier-not-only-salty", Component: SaltAsAmplifierNotOnlySalty },
  { path: "sauce-science/water-content-hidden-dilution", Component: WaterContentHiddenDilution },
  { path: "sauce-science/emulsion-vs-non-emulsion-sauces", Component: EmulsionVsNonEmulsionSauces },
  { path: "sauce-science/reduction-curve-nonlinear-flavor", Component: ReductionCurveNonlinearFlavor },
  { path: "sauce-science/one-change-rule-sauce-debugging", Component: OneChangeRuleSauceDebugging },
  { path: "sauce-science/umami-axis-beyond-salt-acid-fat-sweet", Component: UmamiAxisBeyondSaltAcidFatSweet },
  { path: "sauce-science/brown-gravy-stock-based", Component: BrownGravyStockBased },
  { path: "sauce-science/white-gravy-southern", Component: WhiteGravySouthern },
  { path: "sauce-science/lemon-pan-sauce", Component: LemonPanSauce },
  { path: "sauce-science/mustard-pan-sauce", Component: MustardPanSauce },
  { path: "sauce-science/mushroom-cream-sauce", Component: MushroomCreamSauce },
  { path: "sauce-science/sweet-tomato-sauce", Component: SweetTomatoSauce },
  { path: "sauce-science/spicy-tomato-sauce", Component: SpicyTomatoSauce },
  { path: "sauce-science/balsamic-glaze", Component: BalsamicGlaze },
  { path: "sauce-science/stock-reduction-demi", Component: StockReductionDemi },
  { path: "sauce-science/teriyaki-glaze", Component: TeriyakiGlaze },
  { path: "sauce-science/garlic-soy-sauce", Component: GarlicSoySauce },
  { path: "sauce-science/nacho-cheese-sauce", Component: NachoCheeseSauce },
  { path: "sauce-science/mornay-sauce", Component: MornaySauce },
  { path: "sauce-science/basil-pesto", Component: BasilPesto },
  { path: "cake-science/why-cakes-oil-out", Component: WhyCakesOilOut },
  { path: "cake-science/why-cakes-taste-flat", Component: WhyCakesTasteFlat },
  { path: "cake-science/why-cakes-form-a-thick-crust", Component: WhyCakesFormAThickCrust },
  { path: "cake-science/why-cakes-stick-to-themselves-when-layering", Component: WhyCakesStickToThemselvesWhenLayering },
  { path: "cake-science/why-cakes-lose-height-after-frosting", Component: WhyCakesLoseHeightAfterFrosting },
  { path: "pie-science/why-pie-fillings-taste-bland", Component: WhyPieFillingsTasteBland },
  { path: "pie-science/why-fruit-pies-turn-grainy", Component: WhyFruitPiesTurnGrainy },
  { path: "pie-science/why-custard-pies-crack", Component: WhyCustardPiesCrack },
  { path: "pie-science/why-pie-crust-blisters", Component: WhyPieCrustBlisters },
  { path: "pie-science/why-double-crust-pies-trap-steam", Component: WhyDoubleCrustPiesTrapSteam },
  { path: "ice-cream-science/why-ice-cream-tastes-too-sweet", Component: WhyIceCreamTastesTooSweet },
  { path: "ice-cream-science/why-ice-cream-doesnt-scoop-smoothly", Component: WhyIceCreamDoesntScoopSmoothly },
  { path: "ice-cream-science/why-ice-cream-loses-air-overrun-collapse", Component: WhyIceCreamLosesAirOverrunCollapse },
  { path: "ice-cream-science/why-ice-cream-develops-ice-layers-over-time", Component: WhyIceCreamDevelopsIceLayersOverTime },
  { path: "ice-cream-science/why-ice-cream-base-curdles-before-churning", Component: WhyIceCreamBaseCurdlesBeforeChurning },
  { path: "sauce-science/why-sauces-break-when-reheated", Component: WhySaucesBreakWhenReheated },
  { path: "sauce-science/why-sauces-taste-good-hot-but-flat-cold", Component: WhySaucesTasteGoodHotButFlatCold },
  { path: "sauce-science/why-sauces-separate-on-the-plate", Component: WhySaucesSeparateOnThePlate },
  { path: "sauce-science/why-sauces-taste-metallic", Component: WhySaucesTasteMetallic },
  { path: "sauce-science/why-sauces-clash-with-protein", Component: WhySaucesClashWithProtein },
  { path: "bread-science/why-bread-smells-yeasty", Component: WhyBreadSmellsYeasty },
  { path: "bread-science/why-bread-has-no-flavor", Component: WhyBreadHasNoFlavor },
  { path: "bread-science/why-bread-crumb-is-too-tight", Component: WhyBreadCrumbIsTooTight },
  { path: "bread-science/why-bread-has-large-holes", Component: WhyBreadHasLargeHoles },
  { path: "bread-science/why-bread-dough-tears-instead-of-stretching", Component: WhyBreadDoughTearsInsteadOfStretching },
  { path: "cookie-science/why-cookies-taste-floury", Component: WhyCookiesTasteFloury },
  { path: "cookie-science/why-cookies-have-no-depth-of-flavor", Component: WhyCookiesHaveNoDepthOfFlavor },
  { path: "cookie-science/why-cookies-stick-to-each-other-after-baking", Component: WhyCookiesStickToEachOtherAfterBaking },
  { path: "cookie-science/why-cookies-puff-instead-of-spread", Component: WhyCookiesPuffInsteadOfSpread },
  { path: "cookie-science/why-cookies-taste-better-the-next-day", Component: WhyCookiesTasteBetterTheNextDay },
  { path: "coffee-science/why-coffee-tastes-thin-but-bitter", Component: WhyCoffeeTastesThinButBitter },
  { path: "coffee-science/why-coffee-aroma-doesnt-match-taste", Component: WhyCoffeeAromaDoesntMatchTaste },
  { path: "coffee-science/why-coffee-tastes-better-at-certain-temperatures", Component: WhyCoffeeTastesBetterAtCertainTemperatures },
  { path: "coffee-science/why-coffee-water-chemistry-matters", Component: WhyCoffeeWaterChemistryMatters },
  { path: "coffee-science/why-espresso-channels", Component: WhyEspressoChannels },
];
